

        export const get_HotMovies = 'get_HotMovies'
        export const get_FreeMovies = 'get_FreeMovies'
        export const get_NewMovies = 'get_NewMovies'
        export const get_FictionBooks = 'get_FictionBooks'
        export const get_UnFictionBooks = 'get_UnFictionBooks'
        export const get_RecommendFeed = 'get_RecommendFeed'
        export const set_IsMore = 'set_IsMore'
        export const get_StoreHeader = 'get_StoreHeader'
        export const set_RecommendDate = 'set_RecommendDate'
        export const get_RecommendBefore = 'get_RecommendBefore'
        export const get_ArrayRecommend = 'get_ArrayRecommend'
        export const set_Movie = 'set_Movie'
        export const set_Book = 'set_Book'
        export const set_GroupOfMovie = 'set_GroupOfMovie'
        export const set_GroupOfBook = 'set_GroupOfBook'
        export const set_GroupOfNew = 'set_GroupOfNew'
        export const set_GroupOfSameCity = 'set_GroupOfSameCity'
        export const set_GroupOfMusic = 'set_GroupOfMusic'
        export const set_GroupOfWorkPlace = 'set_GroupOfWorkPlace'